#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
ENV_FILE=".gcp-demo.env"

banner "MotionPatch private GCP demo deployment"

stage "Check local tools and sign in"
say "Run this wizard from Git Bash or WSL in the repository root."
if ! command -v gcloud >/dev/null 2>&1; then
  open_url "https://cloud.google.com/sdk/docs/install"
  warn "Install the Google Cloud CLI, reopen this terminal, and run the wizard again."
  exit 1
fi
if [[ ! -f backend/main.py || ! -f frontend/package.json ]]; then
  warn "Run the wizard from the G-Hack repository root."
  exit 1
fi
if ! gcloud auth list --filter=status:ACTIVE --format='value(account)' | grep -q .; then
  gcloud auth login
fi
ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -n1)
say "Signed in as $ACTIVE_ACCOUNT."
pause "Press Enter to choose the project."

stage "Choose the project and billing account"
open_url "https://console.cloud.google.com/projectselector2/home/dashboard"
step "Use an existing empty project or create one. Copy its project ID, not its display name."
ask GCP_PROJECT_ID "Project ID:"
if [[ ! "$GCP_PROJECT_ID" =~ ^[a-z][a-z0-9-]{4,28}[a-z0-9]$ ]]; then
  warn "That does not look like a valid Google Cloud project ID."
  exit 1
fi
if ! gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  confirm "Project $GCP_PROJECT_ID does not exist. Create it now?" || exit 1
  gcloud projects create "$GCP_PROJECT_ID"
fi
gcloud config set project "$GCP_PROJECT_ID"
CURRENT_BILLING=$(gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingAccountName)' 2>/dev/null || true)
if [[ -z "$CURRENT_BILLING" ]]; then
  open_url "https://console.cloud.google.com/billing"
  step "Open My Billing Account and copy its billing account ID."
  ask GCP_BILLING_ACCOUNT "Billing account ID:"
  GCP_BILLING_ACCOUNT=${GCP_BILLING_ACCOUNT#billingAccounts/}
  confirm "Link project $GCP_PROJECT_ID to billing account $GCP_BILLING_ACCOUNT?" || exit 1
  gcloud billing projects link "$GCP_PROJECT_ID" --billing-account="$GCP_BILLING_ACCOUNT"
else
  GCP_BILLING_ACCOUNT=${CURRENT_BILLING#billingAccounts/}
  say "The project is already linked to billing account $GCP_BILLING_ACCOUNT."
fi
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_BILLING_ACCOUNT "$GCP_BILLING_ACCOUNT"

stage "Create a credit guardrail"
say "The default budget is 250 USD, leaving 50 USD of your credit as a buffer."
ask GCP_BUDGET_AMOUNT "Budget amount, or Enter for 250USD:"
GCP_BUDGET_AMOUNT=${GCP_BUDGET_AMOUNT:-250USD}
gcloud services enable billingbudgets.googleapis.com
if ! gcloud billing budgets list --billing-account="$GCP_BILLING_ACCOUNT" --filter='displayName=MotionPatch demo budget' --format='value(name)' | grep -q .; then
  gcloud billing budgets create --billing-account="$GCP_BILLING_ACCOUNT" --display-name="MotionPatch demo budget" --budget-amount="$GCP_BUDGET_AMOUNT" --threshold-rule=percent=0.50 --threshold-rule=percent=0.80 --threshold-rule=percent=1.00
else
  say "The MotionPatch demo budget already exists."
fi
warn "Budget alerts send email. They do not stop resources automatically."
write_env GCP_BUDGET_AMOUNT "$GCP_BUDGET_AMOUNT"
pause "Press Enter after checking that billing emails reach you."

stage "Enable APIs and create the VM identity"
gcloud services enable compute.googleapis.com aiplatform.googleapis.com iam.googleapis.com iap.googleapis.com
ask GCP_SERVICE_ACCOUNT "Service account name, or Enter for motionpatch-runtime:"
GCP_SERVICE_ACCOUNT=${GCP_SERVICE_ACCOUNT:-motionpatch-runtime}
GCP_SERVICE_ACCOUNT_EMAIL="$GCP_SERVICE_ACCOUNT@$GCP_PROJECT_ID.iam.gserviceaccount.com"
if ! gcloud iam service-accounts describe "$GCP_SERVICE_ACCOUNT_EMAIL" >/dev/null 2>&1; then
  gcloud iam service-accounts create "$GCP_SERVICE_ACCOUNT" --display-name="MotionPatch runtime"
fi
gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" --member="serviceAccount:$GCP_SERVICE_ACCOUNT_EMAIL" --role="roles/aiplatform.user" --condition=None >/dev/null
write_env GCP_SERVICE_ACCOUNT "$GCP_SERVICE_ACCOUNT"
write_env GCP_SERVICE_ACCOUNT_EMAIL "$GCP_SERVICE_ACCOUNT_EMAIL"

stage "Create the private demo VM"
say "Start with 2 vCPU and 8 GiB. Resize later only if a measured repair is too slow."
ask GCP_REGION "Region, or Enter for asia-southeast1:"
GCP_REGION=${GCP_REGION:-asia-southeast1}
ask GCP_ZONE "Zone, or Enter for ${GCP_REGION}-b:"
GCP_ZONE=${GCP_ZONE:-${GCP_REGION}-b}
ask GCP_VM_NAME "VM name, or Enter for motionpatch-demo:"
GCP_VM_NAME=${GCP_VM_NAME:-motionpatch-demo}
if ! gcloud compute networks describe motionpatch-net >/dev/null 2>&1; then
  gcloud compute networks create motionpatch-net --subnet-mode=custom
fi
if ! gcloud compute networks subnets describe motionpatch-subnet --region="$GCP_REGION" >/dev/null 2>&1; then
  gcloud compute networks subnets create motionpatch-subnet --network=motionpatch-net --region="$GCP_REGION" --range=10.42.0.0/24
fi
if ! gcloud compute firewall-rules describe motionpatch-iap-ssh >/dev/null 2>&1; then
  gcloud compute firewall-rules create motionpatch-iap-ssh --network=motionpatch-net --direction=INGRESS --action=ALLOW --rules=tcp:22 --source-ranges=35.235.240.0/20 --target-tags=iap-ssh
fi
if ! gcloud compute instances describe "$GCP_VM_NAME" --zone="$GCP_ZONE" >/dev/null 2>&1; then
  confirm "Create the $GCP_VM_NAME VM and begin using your GCP credit?" || exit 1
  gcloud compute instances create "$GCP_VM_NAME" --zone="$GCP_ZONE" --machine-type=e2-standard-2 --image-family=ubuntu-2404-lts-amd64 --image-project=ubuntu-os-cloud --boot-disk-type=pd-balanced --boot-disk-size=30GB --network=motionpatch-net --subnet=motionpatch-subnet --tags=iap-ssh --metadata=enable-oslogin=TRUE --service-account="$GCP_SERVICE_ACCOUNT_EMAIL" --scopes=cloud-platform
else
  say "VM $GCP_VM_NAME already exists."
fi
write_env GCP_REGION "$GCP_REGION"
write_env GCP_ZONE "$GCP_ZONE"
write_env GCP_VM_NAME "$GCP_VM_NAME"
pause "Wait about one minute for SSH to become ready, then press Enter."

stage "Keep the VM available"
say "The VM will remain running continuously until you stop it manually."
ATTACHED_POLICIES=$(gcloud compute instances describe "$GCP_VM_NAME" --zone="$GCP_ZONE" --format='value(resourcePolicies)' || true)
if [[ "$ATTACHED_POLICIES" == *motionpatch-nightly-stop* ]]; then
  gcloud compute instances remove-resource-policies "$GCP_VM_NAME" --zone="$GCP_ZONE" --resource-policies=motionpatch-nightly-stop
fi
warn "A continuously running VM incurs compute charges every hour."
pause "Press Enter to upload the application."

stage "Upload the current repository"
say "The archive excludes local credentials, virtual environments, databases, uploads, dependencies, and Git history."
DEPLOY_ARCHIVE=$(mktemp --suffix=.tgz)
tar --exclude='.git' --exclude='.env' --exclude='.env.*' --exclude='.gcp-demo.env' --exclude='backend/venv' --exclude='backend/mocap_studio.db' --exclude='backend/uploads' --exclude='frontend/node_modules' --exclude='frontend/dist' --exclude='.pytest_cache' --exclude='__pycache__' -czf "$DEPLOY_ARCHIVE" .
gcloud compute scp "$DEPLOY_ARCHIVE" "$GCP_VM_NAME:motionpatch-source.tgz" --zone="$GCP_ZONE" --tunnel-through-iap
rm -f "$DEPLOY_ARCHIVE"
say "Source uploaded without local data or credential files."
pause "Press Enter to install the application."

stage "Install and start MotionPatch"
say "This installs system packages, builds the frontend and Blender image, starts ClickHouse, and creates the FastAPI service."
BOOTSTRAP_SCRIPT=$(mktemp --suffix=.sh)
cat > "$BOOTSTRAP_SCRIPT" <<BOOTSTRAP
#!/usr/bin/env bash
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io python3-venv python3-pip nginx rsync curl
systemctl enable --now docker nginx
id -u motionpatch >/dev/null 2>&1 || useradd --system --create-home --shell /usr/sbin/nologin motionpatch
usermod -aG docker motionpatch
mkdir -p /opt/motionpatch
rm -rf /tmp/motionpatch-source
mkdir -p /tmp/motionpatch-source
tar -xzf "\$1" -C /tmp/motionpatch-source
rsync -a --delete --exclude='backend/mocap_studio.db' --exclude='backend/uploads/' /tmp/motionpatch-source/ /opt/motionpatch/
mkdir -p /opt/motionpatch/backend/uploads
sed -i 's#http://localhost:8000##g' \$(grep -rl 'http://localhost:8000' /opt/motionpatch/frontend/src)
python3 -m venv /opt/motionpatch/backend/venv
/opt/motionpatch/backend/venv/bin/pip install --no-cache-dir --upgrade pip
/opt/motionpatch/backend/venv/bin/pip install --no-cache-dir fastapi==0.141.1 'uvicorn[standard]==0.52.4' pydantic==2.13.5 python-multipart==0.0.32 google-adk==2.8.0 google-cloud-aiplatform==2.0.1 clickhouse-connect==1.7.2 mcp==1.29.1
CLICKHOUSE_ENV=/etc/motionpatch-clickhouse.env
if [[ ! -f "\$CLICKHOUSE_ENV" ]]; then
  umask 077
  printf 'CLICKHOUSE_USER=default\nCLICKHOUSE_PASSWORD=%s\n' "\$(python3 -c 'import secrets; print(secrets.token_hex(24))')" > "\$CLICKHOUSE_ENV"
fi
set -a
source "\$CLICKHOUSE_ENV"
set +a
docker rm -f motionpatch-clickhouse >/dev/null 2>&1 || true
docker run -d --name motionpatch-clickhouse --restart unless-stopped --memory=2g --cpus=0.75 -e CLICKHOUSE_USER="\$CLICKHOUSE_USER" -e CLICKHOUSE_PASSWORD="\$CLICKHOUSE_PASSWORD" -e CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 -p 127.0.0.1:8123:8123 -p 127.0.0.1:9000:9000 -v motionpatch_clickhouse_data:/var/lib/clickhouse clickhouse/clickhouse-server:26.3.30.9 >/dev/null
docker build -t headless-blender -f /opt/motionpatch/backend/Dockerfile.blender /opt/motionpatch/backend
docker run --rm -v /opt/motionpatch/frontend:/app -w /app node:22-bookworm bash -lc 'npm ci && npm run build'
docker image rm node:22-bookworm >/dev/null 2>&1 || true
rm -rf /opt/motionpatch/frontend/node_modules
apt-get clean
rm -rf /var/lib/apt/lists/*
chown -R motionpatch:motionpatch /opt/motionpatch
for attempt in \$(seq 1 30); do
  curl -fsS -u "\$CLICKHOUSE_USER:\$CLICKHOUSE_PASSWORD" http://127.0.0.1:8123/ping >/dev/null && break
  sleep 2
done
curl -fsS -u "\$CLICKHOUSE_USER:\$CLICKHOUSE_PASSWORD" http://127.0.0.1:8123/ping >/dev/null
sudo -u motionpatch env GOOGLE_CLOUD_PROJECT="$GCP_PROJECT_ID" GOOGLE_CLOUD_LOCATION=global GOOGLE_GENAI_USE_VERTEXAI=true CLICKHOUSE_HOST=127.0.0.1 CLICKHOUSE_PORT=8123 CLICKHOUSE_USER="\$CLICKHOUSE_USER" CLICKHOUSE_PASSWORD="\$CLICKHOUSE_PASSWORD" /opt/motionpatch/backend/venv/bin/python /opt/motionpatch/backend/init_clickhouse.py
cat > /etc/systemd/system/motionpatch.service <<SERVICE
[Unit]
Description=MotionPatch FastAPI
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
User=motionpatch
Group=motionpatch
SupplementaryGroups=docker
WorkingDirectory=/opt/motionpatch/backend
Environment=GOOGLE_CLOUD_PROJECT=$GCP_PROJECT_ID
Environment=GOOGLE_CLOUD_LOCATION=global
Environment=GOOGLE_GENAI_USE_VERTEXAI=true
Environment=CLICKHOUSE_HOST=127.0.0.1
Environment=CLICKHOUSE_PORT=8123
EnvironmentFile=/etc/motionpatch-clickhouse.env
ExecStart=/opt/motionpatch/backend/venv/bin/uvicorn main:app --host 127.0.0.1 --port 8000 --workers 1
Restart=on-failure
RestartSec=5
PrivateTmp=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
SERVICE
cat > /etc/nginx/sites-available/motionpatch <<'NGINX'
server {
    listen 80 default_server;
    server_name _;
    root /opt/motionpatch/frontend/dist;
    index index.html;
    client_max_body_size 30m;

    location ~ ^/(upload|sessions|assets|analyses|repair-plans|runs|bvh|generate_code|run_blender|workflow-sessions|batch_process|feedback|ground-truth)(/|$) {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINX
rm -f /etc/nginx/sites-enabled/default
ln -sfn /etc/nginx/sites-available/motionpatch /etc/nginx/sites-enabled/motionpatch
nginx -t
systemctl daemon-reload
systemctl enable --now motionpatch
systemctl restart nginx
for attempt in \$(seq 1 30); do
  curl -fsS http://127.0.0.1:8000/sessions >/dev/null 2>&1 && break
  sleep 2
done
if ! curl -fsS http://127.0.0.1:8000/sessions >/dev/null; then
  systemctl --no-pager --full status motionpatch || true
  journalctl -u motionpatch -n 80 --no-pager || true
  exit 1
fi
rm -rf /tmp/motionpatch-source
BOOTSTRAP
gcloud compute scp "$BOOTSTRAP_SCRIPT" "$GCP_VM_NAME:motionpatch-bootstrap.sh" --zone="$GCP_ZONE" --tunnel-through-iap
rm -f "$BOOTSTRAP_SCRIPT"
confirm "Replace deployed code while preserving the VM database and uploads?" || exit 1
gcloud compute ssh "$GCP_VM_NAME" --zone="$GCP_ZONE" --tunnel-through-iap --command='sudo bash ~/motionpatch-bootstrap.sh ~/motionpatch-source.tgz'
say "MotionPatch is running on the VM."

stage "Verify the services"
gcloud compute ssh "$GCP_VM_NAME" --zone="$GCP_ZONE" --tunnel-through-iap --command="sudo systemctl --no-pager --full status motionpatch | head -n 12; sudo docker ps --format 'table {{.Names}}\t{{.Status}}'; curl -fsS http://127.0.0.1:8000/sessions"
say "You should see an active motionpatch service, a running ClickHouse container, and a JSON sessions response."
pause "Press Enter after the checks pass."

stage "Open the private demo"
say "Keep the next command running while you use the app."
say "Open http://localhost:8080 after the tunnel connects."
say "Command: gcloud compute ssh $GCP_VM_NAME --project=$GCP_PROJECT_ID --zone=$GCP_ZONE --tunnel-through-iap --ssh-flag=\"-N\" --ssh-flag=\"-L 8080:127.0.0.1:80\""
say "Stop the tunnel with Ctrl-C. Stop the VM when you finish:"
say "gcloud compute instances stop $GCP_VM_NAME --zone=$GCP_ZONE"
say "Start it later with:"
say "gcloud compute instances start $GCP_VM_NAME --zone=$GCP_ZONE"
warn "Do not create a firewall rule for ports 80, 8000, 8123, or 9000. The backend is not safe for anonymous internet traffic yet."
pause "Run the tunnel command in a second Git Bash window, then press Enter here."
open_url "http://localhost:8080"

finish
