#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE=".gcp-demo.env"

banner "MotionPatch code redeployment"

stage "Validate the existing VM"
if ! command -v gcloud >/dev/null 2>&1; then
  warn "Google Cloud CLI is not available."
  exit 1
fi
if [[ ! -f backend/main.py || ! -f frontend/package.json ]]; then
  warn "Run this wizard from the G-Hack repository root."
  exit 1
fi
if [[ ! -f "$ENV_FILE" ]]; then
  warn "$ENV_FILE is missing. Run tools/gcp_demo_wizard.sh once before using this redeploy wizard."
  exit 1
fi
set -a
source "$ENV_FILE"
set +a
for key in GCP_PROJECT_ID GCP_ZONE GCP_VM_NAME; do
  if [[ -z "${!key:-}" ]]; then
    warn "$key is missing from $ENV_FILE. Run tools/gcp_demo_wizard.sh once to repair the setup."
    exit 1
  fi
done
if ! gcloud auth list --filter=status:ACTIVE --format='value(account)' | grep -q .; then
  warn "No active Google Cloud login. Run gcloud auth login, then retry."
  exit 1
fi
VM_STATUS=$(gcloud compute instances describe "$GCP_VM_NAME" --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE" --format='value(status)')
if [[ "$VM_STATUS" == "TERMINATED" ]]; then
  confirm "The VM is stopped. Start it now?" || exit 1
  gcloud compute instances start "$GCP_VM_NAME" --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE"
  for attempt in $(seq 1 30); do
    VM_STATUS=$(gcloud compute instances describe "$GCP_VM_NAME" --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE" --format='value(status)')
    [[ "$VM_STATUS" == "RUNNING" ]] && break
    sleep 2
  done
fi
if [[ "$VM_STATUS" != "RUNNING" ]]; then
  warn "VM $GCP_VM_NAME is $VM_STATUS, not RUNNING."
  exit 1
fi
say "Using $GCP_VM_NAME in $GCP_ZONE."
pause "Press Enter to package the current code."

stage "Upload the current code"
confirm "Upload the current repository to $GCP_VM_NAME?" || exit 1
DEPLOY_ARCHIVE=$(mktemp --suffix=.tgz)
BOOTSTRAP_SCRIPT=""
cleanup() {
  rm -f "$DEPLOY_ARCHIVE"
  [[ -n "$BOOTSTRAP_SCRIPT" ]] && rm -f "$BOOTSTRAP_SCRIPT"
}
trap cleanup EXIT
tar --exclude='.git' --exclude='.env' --exclude='.env.*' --exclude='.gcp-demo.env' --exclude='backend/venv' --exclude='backend/mocap_studio.db' --exclude='backend/uploads' --exclude='frontend/node_modules' --exclude='frontend/dist' --exclude='.pytest_cache' --exclude='__pycache__' -czf "$DEPLOY_ARCHIVE" .
gcloud compute scp "$DEPLOY_ARCHIVE" "$GCP_VM_NAME:motionpatch-source.tgz" --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE" --tunnel-through-iap
say "Code uploaded. Local credentials, data, dependencies, and Git history were excluded."
pause "Press Enter to replace the deployed code."

stage "Build and restart MotionPatch"
confirm "Deploy the uploaded code while preserving the VM database and uploads?" || exit 1
BOOTSTRAP_SCRIPT=$(mktemp --suffix=.sh)
cat > "$BOOTSTRAP_SCRIPT" <<'BOOTSTRAP'
#!/usr/bin/env bash
set -euo pipefail
for path in /opt/motionpatch/backend/venv /etc/motionpatch-clickhouse.env /etc/systemd/system/motionpatch.service; do
  [[ -e "$path" ]] || { printf 'Missing required setup: %s\nRun tools/gcp_demo_wizard.sh once.\n' "$path"; exit 1; }
done
rm -rf /tmp/motionpatch-source
mkdir -p /tmp/motionpatch-source
tar -xzf "$1" -C /tmp/motionpatch-source
rsync -a --delete --exclude='.env' --exclude='.env.*' --exclude='backend/venv/' --exclude='backend/mocap_studio.db' --exclude='backend/uploads/' --exclude='frontend/dist/' --exclude='frontend/node_modules/' /tmp/motionpatch-source/ /opt/motionpatch/
mkdir -p /opt/motionpatch/backend/uploads
mapfile -t localhost_files < <(grep -rl 'http://localhost:8000' /opt/motionpatch/frontend/src || true)
if (( ${#localhost_files[@]} )); then
  sed -i 's#http://localhost:8000##g' "${localhost_files[@]}"
fi
docker start motionpatch-clickhouse >/dev/null
docker build -t headless-blender -f /opt/motionpatch/backend/Dockerfile.blender /opt/motionpatch/backend
docker run --rm -v /opt/motionpatch/frontend:/app -w /app node:22-bookworm bash -lc 'npm ci && npm run build'
chown -R motionpatch:motionpatch /opt/motionpatch
set -a
source /etc/motionpatch-clickhouse.env
set +a
for attempt in $(seq 1 30); do
  curl -fsS -u "$CLICKHOUSE_USER:$CLICKHOUSE_PASSWORD" http://127.0.0.1:8123/ping >/dev/null 2>&1 && break
  sleep 2
done
curl -fsS -u "$CLICKHOUSE_USER:$CLICKHOUSE_PASSWORD" http://127.0.0.1:8123/ping >/dev/null
sudo -u motionpatch env GOOGLE_CLOUD_PROJECT="$GCP_PROJECT_ID" GOOGLE_CLOUD_LOCATION=global GOOGLE_GENAI_USE_VERTEXAI=true CLICKHOUSE_HOST=127.0.0.1 CLICKHOUSE_PORT=8123 CLICKHOUSE_USER="$CLICKHOUSE_USER" CLICKHOUSE_PASSWORD="$CLICKHOUSE_PASSWORD" /opt/motionpatch/backend/venv/bin/python /opt/motionpatch/backend/init_clickhouse.py
systemctl restart motionpatch nginx
for attempt in $(seq 1 30); do
  curl -fsS http://127.0.0.1:8000/sessions >/dev/null 2>&1 && break
  sleep 2
done
if ! curl -fsS http://127.0.0.1:8000/sessions >/dev/null; then
  systemctl --no-pager --full status motionpatch || true
  journalctl -u motionpatch -n 80 --no-pager || true
  exit 1
fi
curl -fsS http://127.0.0.1:80 >/dev/null
rm -rf /tmp/motionpatch-source
BOOTSTRAP
gcloud compute scp "$BOOTSTRAP_SCRIPT" "$GCP_VM_NAME:motionpatch-redeploy.sh" --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE" --tunnel-through-iap
gcloud compute ssh "$GCP_VM_NAME" --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE" --tunnel-through-iap --command='sudo env GCP_PROJECT_ID='"$GCP_PROJECT_ID"' bash ~/motionpatch-redeploy.sh ~/motionpatch-source.tgz'
say "The new code is running."

stage "Verify and open the demo"
gcloud compute ssh "$GCP_VM_NAME" --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE" --tunnel-through-iap --command="printf 'SERVICE: '; sudo systemctl is-active motionpatch; printf 'CLICKHOUSE: '; sudo docker inspect -f '{{.State.Status}}' motionpatch-clickhouse; printf 'API: '; curl -fsS http://127.0.0.1:8000/sessions"
say "Run this in a second Git Bash window and keep it open:"
say "gcloud compute ssh $GCP_VM_NAME --project=$GCP_PROJECT_ID --zone=$GCP_ZONE --tunnel-through-iap --ssh-flag=\"-N\" --ssh-flag=\"-L 8080:127.0.0.1:80\""
say "Then open http://localhost:8080 and press Ctrl+Shift+R."

finish

